django_lx/django-vo_te/vo_te/urls.py
from django.conf.urls import url

from . import views
app_name='vo_te'
urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(),name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

django_lx/django-vo_te/vo_te/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)#模型字段
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    '''def test(self):
    #打印查看是否在最近一天发布的
        now = timezone.now()
        print(now)
        print(self.pub_date)
        now1 = now - datetime.timedelta(days=1)
        print(now1)
        '''
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field='pub_date'
    was_published_recently.boolean=True
    #简要说明
    was_published_recently.short_description='是否在最近的一天发布?'
class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_lx/django-vo_te/vo_te/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views import generic
from .models import Choice,Question
from django.utils import timezone
# Create your views here.

class IndexView(generic.ListView):
    template_name='vo_te/index.html'
    context_object_name='latest_question_list'

    def get_queryset(self):
        '''返回最新的五个已发布的问题'''
        return Question.objects.filter(
            #lte意味着返回所有pub_date小于或等于timezone.now(),lts是小于
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name='vo_te/detail.html'
    def get_queryset(self):
        '''返回最新的五个已发布的问题'''
        # lte意味着返回所有pub_date小于或等于timezone.now(),lts是小于
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name='vo_te/results.html'

def vote(request,question_id):
    p=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=p.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'vo_te/detail.html',{
            'question':p,
            'error_message':"You didn't select a choice."
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        #成功处理投票的数据后，自动跳转到结果页面，防止用户连续多次提交。
        return HttpResponseRedirect(reverse('vo_te:results',args=(p.id,)))

'''def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[:5]
    #output=','.join([q.question_text for q in latest_question_list])
    context={'latest_question_list':latest_question_list}
    return render(request,'vo_te/index.html',context)

def detail(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'vo_te/detail.html',{'question':question})

def results(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'vo_te/results.html',{'question':question})
'''

django_lx/django-vo_te/vo_te/templates/vo_te/detail.html
<h1>{{ question.question_text}}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<form action="{% url 'vo_te:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br/>
{% endfor %}
<input type="submit" value="Vote"/>
</form>

django_lx/django-vo_te/vo_te/templates/vo_te/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vo_te/style.css' %}"/>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list%}
        <li><a href="{% url 'vo_te:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No vo_te are available.</p>
{% endif %}

django_lx/django-vo_te/vo_te/templates/vo_te/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}--{{ choice.votes }}--vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>
<a href="{% url 'vo_te:detail' question.id %}">Vote again?</a>